def build_prompt(mission: dict, last_report: dict | None = None) -> str:
    parts = [
        "You are a DevFleet coding agent. Execute the following mission autonomously and completely.",
        "Work through the task step by step. Write clean, production-quality code.",
        "",
        f"## Mission: {mission['title']}",
        "",
        mission["detailed_prompt"],
    ]

    if mission.get("acceptance_criteria"):
        parts += ["", "## Acceptance Criteria", mission["acceptance_criteria"]]

    if last_report:
        parts += [
            "",
            "## Previous Session Context",
            f"**What was done:** {last_report.get('what_done', 'N/A')}",
            f"**What was left open:** {last_report.get('what_open', 'N/A')}",
            f"**Recommended next steps:** {last_report.get('next_steps', 'N/A')}",
            "",
            "Continue from where the previous session left off. Do NOT redo completed work.",
        ]

    parts += [
        "",
        "## CRITICAL: End-of-Mission — Preview & Report",
        "",
        "When you have finished ALL work, do the following TWO things:",
        "",
        "### Step 1: Start a preview server",
        "If the project has a UI or web output, start a local preview server so the user can review:",
        "- For static sites (Astro, Hugo, etc.): run `python3 -m http.server 4321 --bind 0.0.0.0` from the build output directory (e.g. `dist/`)",
        "- For Node.js apps: run `npx serve -l 4321` or the project's `preview` script on port 4321",
        "- For Python web apps: start with `--port 4321 --host 0.0.0.0`",
        "- Always use port **4321** and bind to **0.0.0.0**",
        "- If the project has no UI (CLI tool, library, backend-only API), skip this step",
        "- Leave the server running — do NOT stop it",
        "",
        "### Step 2: Submit your report",
        "You MUST submit a report when done. Use the `submit_report` tool if available (preferred),",
        "otherwise output the report in text format between markers.",
        "",
        "**Option A (preferred): Call the `submit_report` tool with these fields:**",
        "- files_changed: list of files you created/modified/deleted",
        "- what_done: what you completed",
        "- what_open: what remains (or 'None')",
        "- what_tested: tests you ran and results",
        "- what_untested: areas lacking coverage (or 'None')",
        "- next_steps: recommendations for next session (or 'None — mission complete')",
        "- errors_encountered: any errors or blockers (or 'None')",
        "- preview_url: http://localhost:4321 or 'None — no UI'",
        "",
        "**Option B (fallback): Output in this EXACT text format:**",
        "",
        "---DEVFLEET-REPORT-START---",
        "## Files Changed",
        "- path/to/file.py (created|modified|deleted)",
        "",
        "## What's Done",
        "- Completed item 1",
        "- Completed item 2",
        "",
        "## What's Open",
        "- Remaining item 1 (or 'None' if everything is done)",
        "",
        "## What's Tested",
        "- Test description and result",
        "",
        "## What's Not Tested",
        "- Area lacking coverage (or 'None')",
        "",
        "## Next Steps",
        "- Recommendation for next session (or 'None — mission complete')",
        "",
        "## Errors Encountered",
        "- Error or blocker (or 'None')",
        "",
        "## Preview",
        "- URL: http://localhost:4321 (or 'None — no UI')",
        "---DEVFLEET-REPORT-END---",
    ]

    return "\n".join(parts)
